### ISSUE TITLE
Links have no color

### ISSUE THREAD

**Issue by Geczy** [jch254/starter-pack#4]
https://starter-pack.603.nu/

But they are colored on Rebass demo, see example here http://jxnblk.com/rebass/#Drawer

```css
      a, a:visited, a:hover, a:active {
          text-decoration: none;
          color: inherit;
      }
```

Why was this added to the index.html file?
